spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306/${MYSQL_DATABASE:demo}}?characterEncoding=utf-8
    # 使用druid数据源
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:424926}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  devtools:
#    restart:
#      enabled: true
#    livereload:
#      enabled: true

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss


  flyway:
    validate-on-migrate: false
    locations: classpath:db/migration


server:
  port: ${PORT:8080}


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.mh_entity  # 注意：对应实体类的路径
#
#flyway:
#  validate-on-migrate: false
logging:
  level:
    com.example.demo.mh_dao.StoreMapper:
      debug
